---
## This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: all
  gather_facts: no
  roles:
  - wol-host

- hosts: all
  gather_facts: no
  roles:
  - install-updates
  tags:
  - install-updates
  