---
# This role contains common plays that will run on all nodes.

- name: Send magic Wake-On-Lan packet to {{host_mac}}
  wakeonlan:
    mac: '{{host_mac}}'
  delegate_to: localhost

- name: Wait 300 seconds for system to become reachable
  wait_for_connection:
    timeout: 300

- name: Gather facts for first time
  setup: