---
# This role handles installing updates

- name: Run powershell script with parameter "{{ps_param}}"
  script: files/install.ps1 "{{ps_param}}"

- name: Sending status mail
  community.general.mail:
    host: "{{mailhog_host}}"
    port: 1025
    username: mh@example.com
    password: mysecret
    to: Markus Hosiner <mh@example.com>
    subject: "[AWX:TPL_ROLLOUT_UPDATE:COMPLETE] {{inventory_hostname}}"
    body: "System {{inventory_hostname}} has been successfully updated.\n{{ansible_facts}}"
  delegate_to: localhost 